db-uri = "host=localhost port=5432 user=authenticator password=Postgrest1234 dbname=left_and_right"
db-schemas = "public"
db-anon-role = "web_anon"

server-host = "127.0.0.1"
server-port = 3001

jwt-secret = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
jwt-secret-is-base64 = false
