db-uri = "host=localhost port=5432 user=authenticator password=Postgrest1234 dbname=left_and_right"
db-schemas = "public"
db-anon-role = "web_anon"

server-host = "0.0.0.0"
server-port = 3000

jwt-secret = "4f138892b143692faa8c319f6c899a9f602b14b85d319371658f67f31e0b6592A"
jwt-secret-is-base64 = false
